# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='condpost',
            name='name',
            field=models.CharField(default='namedef', max_length=25),
        ),
    ]
