# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0003_auto_20170924_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulepost',
            name='ruleId',
            field=models.IntegerField(default=1),
        ),
    ]
