# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 06:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0004_auto_20170930_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rulepost',
            name='ruleId',
        ),
    ]
