# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0005_remove_rulepost_ruleid'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulepost',
            name='comments',
            field=models.CharField(default='Initial configuration', max_length=200),
        ),
    ]
