# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0006_rulepost_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rulepost',
            name='ruleInt',
        ),
        migrations.AddField(
            model_name='rulepost',
            name='intge30',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rulepost',
            name='intge60',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rulepost',
            name='intge90',
            field=models.IntegerField(default=0),
        ),
    ]
